### ISSUE TITLE
Calibration don't works

### ISSUE THREAD

**Issue by alekin2** [fracpete/scikit-weka#8]
I tried:
calibrated = CalibratedClassifierCV(model, method='sigmoid', cv=5)
calibrated.fit(train, ytrain)

where model is a WekaEstimator
for example: 
WekaEstimator(classname="weka.classifiers.functions.Logistic",options=["-R","1.0E-8","-M","-1","-num-decimal-places","4"])

I get this error:
TypeError: predict_proba() got an unexpected keyword argument 'X'

**Comment by fracpete** [comment]
I've aligned the argument names of the `fit`, `fit_predict` and `score` methods with sklearn (using `X` and `y`) with [this commit](https://github.com/fracpete/sklearn-weka-plugin/commit/d56b596924397a9392398ce77bd553ccd63273cc). However, the example code now generates another error, which may be a general incompatibility between sklearn and Weka (sklearn treats nominal attributes as numeric ones):

```
ValueError: y contains previously unseen labels: "b'Iris-setosa'"
```

The example code:

```python
import sklweka.jvm as jvm
from sklearn.calibration import CalibratedClassifierCV
from sklweka.classifiers import WekaEstimator
from sklweka.dataset import load_arff

jvm.start(packages=True)

X, y, meta = load_arff("/some/where/iris.arff", class_index="last")

logistic = WekaEstimator(classname="weka.classifiers.functions.Logistic",
                         options=["-R", "1.0E-8", "-M", "-1", "-num-decimal-places", "4"])

calibrated = CalibratedClassifierCV(logistic, method='sigmoid', cv=5)
calibrated.fit(X, y)

jvm.stop()
```

**Comment by fracpete** [comment]
I don't see any way of fixing this. I've linked to this issue so that other users are aware of it:
https://fracpete.github.io/sklearn-weka-plugin/gotchas.html

**Comment by alekin2** [comment]
An alternative solution to use calibration is to leverage weka.classifiers.meta.CascadeGeneralization with pct.
See https://weka.sourceforge.io/packageMetaData/probabilityCalibrationTrees/
